version: '3'

services:
    app:
        build: .
        volumes:
            - .:/app
        depends_on:
            - database
            - composer 

    composer:
        image: composer/composer:php7
        command: install -o
        volumes:
            - .:/app
    
    database:
        image: mysql:5.7
        container_name: database.dev
        command: mysqld --user=root --verbose
        volumes:
            - ./mysql_init:/docker-entrypoint-initdb.d
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'validators'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'test'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'